### ISSUE TITLE
I can't add any of these icons to HipChat

### ISSUE THREAD

**Issue by yagoferrer** [modcloth/hipchat-emoticons#2]
This is the error I'm getting:
The image is too small for an emoticon. Please choose an image that is between 64 and 120 pixels in either width or height. Resizing decreases the quality of the emoticons.

**Comment by webmastir** [comment]
Same here. They need to be resized as HipChat changed the dimensions accepted again

**Comment by rgranadino** [comment]
(sadpanda)

**Comment by joeoftheforsythe** [comment]
Why is no one addressing this?!

**Comment by AdamKalnas** [comment]
@alexschlessinger / @baileyb - you are our only hope.

**Comment by meatballhat** [comment]
![image-dimensions](https://cloud.githubusercontent.com/assets/45143/6584760/eae6894a-c743-11e4-82fa-5f742dc43ec6.jpg)

**Comment by yagoferrer** [comment]
We should just write our own Open Source HipChat App with all the Atlassian integrations. They have plenty APIs...
